import { useT } from '../../i18n';
import {
  API_TAG_ORDER,
  OPENAPI_SPEC,
  collectOpenApiOperations,
  type OpenApiOperation,
  type OpenApiParameter,
  type OpenApiSpec,
} from './docsRegistry';

/**
 * API Reference page (the docs site's signature feature).
 *
 * The spec defaults to the committed OpenAPI artifact
 * (packages/protocol/openapi/agentnet.openapi.json), which is regenerated
 * by scripts/export_openapi.py in CI, so this page is always same-source
 * with the backend and never needs manual sync. Tests may pass a reduced
 * fragment through the `spec` prop.
 */
export default function ApiReferencePage({ spec = OPENAPI_SPEC }: { spec?: OpenApiSpec }) {
  const t = useT();
  const operations = collectOpenApiOperations(spec);

  const groups = groupByTag(operations);

  return (
    <div data-testid="docs-api-reference">
      <h1 className="font-display text-pixel-xl mt-0 mb-4 border-b-2 border-pixel-line pb-2">
        {t('docs.api.title')}
      </h1>
      <p className="mb-6 font-body text-base text-pixel-muted">{t('docs.api.description')}</p>

      {groups.map(([tag, ops]) => (
        <section key={tag} className="mb-8" data-testid="docs-api-tag-group" data-tag={tag}>
          <h2 className="mb-3 border-b-2 border-pixel-line pb-1 font-display text-pixel-lg text-pixel-fg">
            {tagLabel(t, tag)}
          </h2>
          <ul className="flex flex-col gap-4">
            {ops.map((op) => (
              <li key={`${op.method}-${op.path}`}>
                <EndpointCard op={op} />
              </li>
            ))}
          </ul>
        </section>
      ))}
    </div>
  );
}

/** Group operations by first tag, ordered by API_TAG_ORDER then alphabetically. */
function groupByTag(operations: OpenApiOperation[]): Array<[string, OpenApiOperation[]]> {
  const buckets = new Map<string, OpenApiOperation[]>();
  for (const op of operations) {
    const tag = (op.tags?.[0] ?? 'other').trim() || 'other';
    let list = buckets.get(tag);
    if (!list) {
      list = [];
      buckets.set(tag, list);
    }
    list.push(op);
  }
  return [...buckets.entries()].sort(([a], [b]) => {
    const ia = API_TAG_ORDER.indexOf(a);
    const ib = API_TAG_ORDER.indexOf(b);
    if (ia === -1 && ib === -1) return a.localeCompare(b);
    if (ia === -1) return 1;
    if (ib === -1) return -1;
    return ia - ib;
  });
}

function tagLabel(t: (key: string) => string, tag: string): string {
  const localized = t(`docs.api.tag.${tag}`);
  // translate() returns the key itself when missing; fall back to the raw tag.
  return localized === `docs.api.tag.${tag}` ? tag : localized;
}

/**
 * Localized summary/description of one OpenAPI operation.
 *
 * Keys live in the docs namespace as `docs.api.op.<operationId>.summary` and
 * `.description`; both locales mirror the committed OpenAPI artifact (en
 * verbatim, zh translated) and are regenerated by
 * apps/web/src/features/docs/content/gen_api_ops.py. translate() returns the
 * key itself when it is missing everywhere, so that case falls back to the
 * raw spec text; a spec entry without an operationId skips the lookup.
 */
function localizedOpText(
  t: (key: string) => string,
  op: OpenApiOperation,
  field: 'summary' | 'description',
): string | undefined {
  const raw = op[field];
  if (!op.operationId || !raw) return raw;
  const key = `docs.api.op.${op.operationId}.${field}`;
  const localized = t(key);
  return localized === key ? raw : localized;
}

function EndpointCard({ op }: { op: OpenApiOperation }) {
  const t = useT();
  const params = op.parameters ?? [];
  const summary = localizedOpText(t, op, 'summary');
  const description = localizedOpText(t, op, 'description');
  return (
    <div
      className="border-2 border-pixel-line bg-pixel-surface p-4"
      data-testid="docs-api-endpoint"
    >
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
        <span
          className="inline-block w-fit min-w-[68px] border-2 border-pixel-line bg-pixel-raised px-2 text-center font-mono text-pixel-base text-pixel-fg"
        >
          {op.method}
        </span>
        <span className="break-all font-mono text-base text-pixel-fg">{op.path}</span>
      </div>

      {summary && (
        <p className="mt-3 font-body text-base text-pixel-fg">{summary}</p>
      )}
      {description && (
        <p className="mt-2 whitespace-pre-wrap font-body text-base text-pixel-muted">
          {description}
        </p>
      )}

      <h3 className="mt-4 mb-2 font-pixel text-pixel-base text-pixel-fg">
        {t('docs.api.parameters')}
      </h3>
      {params.length === 0 ? (
        <p className="font-body text-base text-pixel-muted">{t('docs.api.noParameters')}</p>
      ) : (
        <div className="w-full overflow-x-auto">
          <table className="w-full border-2 border-pixel-line border-collapse text-left">
            <thead className="bg-pixel-raised">
              <tr>
                <th className="border-2 border-pixel-line px-2 py-1 font-pixel text-pixel-base">
                  {t('docs.api.paramName')}
                </th>
                <th className="border-2 border-pixel-line px-2 py-1 font-pixel text-pixel-base">
                  {t('docs.api.paramIn')}
                </th>
                <th className="border-2 border-pixel-line px-2 py-1 font-pixel text-pixel-base">
                  {t('docs.api.paramType')}
                </th>
                <th className="border-2 border-pixel-line px-2 py-1 font-pixel text-pixel-base">
                  {t('docs.api.paramRequired')}
                </th>
                <th className="border-2 border-pixel-line px-2 py-1 font-pixel text-pixel-base">
                  {t('docs.api.paramDescription')}
                </th>
              </tr>
            </thead>
            <tbody>
              {params.map((param) => (
                <ParamRow key={`${param.in}-${param.name}`} param={param} />
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function ParamRow({ param }: { param: OpenApiParameter }) {
  const t = useT();
  return (
    <tr>
      <td className="break-all border-2 border-pixel-line px-2 py-1 font-mono text-base text-pixel-fg">
        {param.name}
      </td>
      <td className="border-2 border-pixel-line px-2 py-1 font-body text-base text-pixel-fg">
        {param.in}
      </td>
      <td className="border-2 border-pixel-line px-2 py-1 font-mono text-pixel-base text-pixel-fg">
        {paramType(param)}
      </td>
      <td className="border-2 border-pixel-line px-2 py-1 font-body text-base text-pixel-fg">
        {param.required ? t('docs.api.required') : t('docs.api.optional')}
      </td>
      <td className="border-2 border-pixel-line px-2 py-1 font-body text-base text-pixel-muted">
        {param.description ?? '--'}
      </td>
    </tr>
  );
}

function paramType(param: OpenApiParameter): string {
  const type = param.schema?.type;
  if (!type) return '--';
  const format = param.schema?.format;
  const enumCount = param.schema?.enum?.length;
  return format ? `${type}<${format}>` : enumCount ? `${type} (enum)` : type;
}
