services:
  api:
    volumes:
      - ../apps/api/app:/app/app:ro
      - ../apps/api/migrations:/app/migrations:ro
    environment:
      LOG_LEVEL: DEBUG

  web:
    volumes:
      - ../apps/web/src:/app/src:ro

